{
 "title": "Ingress Nginx / Request Handling Performance",
 "description": "A dashboard that monitors Ingress-nginx. It is created using the (Ingress-Nginx-mixin)[https://github.com/adinhodovic/ingress-nginx-mixin]",
 "tags": [
  "nginx",
  "ingress-nginx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "exported_namespace",
    "label": "Ingress Namespace",
    "query": "label_values(nginx_ingress_controller_requests, exported_namespace)"
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": "label_values(nginx_ingress_controller_requests{exported_namespace=~\"$exported_namespace\"}, ingress)"
   },
   { "name": "error_codes", "label": "Error Codes", "query": "4,5" }
  ]
 },
 "panels": [
  { "title": "Ingress Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Request Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le, ingress, exported_namespace)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        ingress =~ \"$ingress\",\n        exported_namespace=~\"$exported_namespace\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": ".5 - {{ ingress }}/{{ exported_namespace }}"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, ingress, exported_namespace)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        ingress =~ \"$ingress\",\n        exported_namespace=~\"$exported_namespace\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": ".95 - {{ ingress }}/{{ exported_namespace }}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, ingress, exported_namespace)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        ingress =~ \"$ingress\",\n        exported_namespace=~\"$exported_namespace\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": ".99 - {{ ingress }}/{{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le, ingress, exported_namespace)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n        ingress =~ \"$ingress\",\n        exported_namespace=~\"$exported_namespace\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": ".5 - {{ ingress }}/{{ exported_namespace }}"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, ingress, exported_namespace)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n        ingress =~ \"$ingress\",\n        exported_namespace=~\"$exported_namespace\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": ".95 - {{ ingress }}/{{ exported_namespace }}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, ingress, exported_namespace)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n        ingress =~ \"$ingress\",\n        exported_namespace=~\"$exported_namespace\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": ".99 - {{ ingress }}/{{ exported_namespace }}"
    }
   ]
  },
  { "title": "Ingress Paths", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (path, ingress, exported_namespace)(\n  rate(\n    nginx_ingress_controller_request_duration_seconds_count{\n      ingress =~ \"$ingress\",\n      exported_namespace=~\"$exported_namespace\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ path }} - {{ ingress }}/{{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "Median upstream response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  .5,\n  sum by (le, path, ingress, exported_namespace)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n        ingress =~ \"$ingress\",\n        exported_namespace=~\"$exported_namespace\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "{{ path }} - {{ ingress }}/{{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "Response error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (path, ingress, exported_namespace) (\n  rate(\n    nginx_ingress_controller_request_duration_seconds_count{\n      ingress=~\"$ingress\",\n      exported_namespace=~\"$exported_namespace\",\n      status=~\"500\"\n    }[$__rate_interval]\n  )\n)\n/\nsum by (path, ingress, exported_namespace) (\n  rate(\n    nginx_ingress_controller_request_duration_seconds_count{\n      ingress =~ \"$ingress\",\n      exported_namespace =~ \"$exported_namespace\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ path }} - {{ ingress }}/{{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "Upstream time consumed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (path, ingress, exported_namespace) (\n  rate(\n    nginx_ingress_controller_response_duration_seconds_sum{\n      ingress =~ \"$ingress\",\n      exported_namespace =~ \"$exported_namespace\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ path }} - {{ ingress }}/{{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "Response error volume",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(\n    nginx_ingress_controller_request_duration_seconds_count{\n      ingress=~\"$ingress\",\n      exported_namespace=~\"$exported_namespace\",\n      status=~\"500\"\n    }[$__rate_interval]\n  )\n) by(path, ingress, exported_namespace, status)\n",
     "legendFormat": "{{ status }} {{ path }} - {{ ingress }}/{{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "Average response size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate (\n      nginx_ingress_controller_response_size_sum {\n        ingress=~\"$ingress\",\n        exported_namespace=~\"$exported_namespace\",\n      }[$__rate_interval]\n  )\n)  by (path, ingress, exported_namespace)\n/\nsum (\n  rate(\n    nginx_ingress_controller_response_size_count {\n        ingress=~\"$ingress\",\n        exported_namespace=~\"$exported_namespace\",\n    }[$__rate_interval]\n  )\n) by (path, ingress, exported_namespace)\n",
     "legendFormat": "{{ path }} - {{ ingress }}/{{ exported_namespace }}"
    }
   ]
  }
 ]
}